from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path

from src import db


class _Cursor:
    rowcount = 1

    def __init__(self, row=None):
        self.row = row
        self.executed = []

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def execute(self, sql, params):
        self.executed.append((sql, params))

    def fetchone(self):
        return self.row


class _Connection:
    def __init__(self, cursor):
        self._cursor = cursor

    def cursor(self):
        return self._cursor


def test_is_configured_accepts_database_url_or_host(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.delenv("DB_HOST", raising=False)
    assert db.is_configured() is False

    monkeypatch.setenv("DATABASE_URL", "postgresql://example.invalid/asset_3d")
    assert db.is_configured() is True

    monkeypatch.delenv("DATABASE_URL")
    monkeypatch.setenv("DB_HOST", "db.internal")
    assert db.is_configured() is True


def test_connect_uses_postgresql_url(monkeypatch):
    captured = {}

    def fake_connect(dsn, **kwargs):
        captured["dsn"] = dsn
        captured["kwargs"] = kwargs
        return object()

    monkeypatch.setenv("DATABASE_URL", "postgresql://db.internal/asset_3d")
    monkeypatch.setenv("DB_STATEMENT_TIMEOUT_MS", "15000")
    monkeypatch.setattr(db, "_driver", lambda: (fake_connect, None))

    db._connect()

    assert captured["dsn"] == "postgresql://db.internal/asset_3d"
    assert captured["kwargs"]["autocommit"] is True
    assert captured["kwargs"]["options"] == "-c statement_timeout=15000"


def test_execute_returning_id_reads_postgresql_returning_row(monkeypatch):
    cursor = _Cursor({"id": 42})

    @contextmanager
    def fake_get_conn():
        yield _Connection(cursor)

    monkeypatch.setattr(db, "get_conn", fake_get_conn)

    result = db.execute_returning_id(
        "INSERT INTO world_asset (label) VALUES (%s) RETURNING id",
        ("tree",),
    )

    assert result == 42
    assert cursor.executed == [
        ("INSERT INTO world_asset (label) VALUES (%s) RETURNING id", ("tree",))
    ]


def test_postgresql_migration_covers_runtime_tables_and_has_no_mysql_syntax():
    root = Path(__file__).resolve().parents[1]
    migration = (root / "migrations" / "001_postgresql_3d_schema.up.sql").read_text(encoding="utf-8")
    runtime_sql = "\n".join(
        [
            (root / "src" / "db.py").read_text(encoding="utf-8"),
            (root / "src" / "api" / "world.py").read_text(encoding="utf-8"),
            (root / "src" / "services" / "media.py").read_text(encoding="utf-8"),
        ]
    )

    required_tables = {
        "agent_settings",
        "agent_media_asset",
        "agent_usage",
        "media_model_catalog",
        "media_model_option",
        "media_model_capability",
        "world_generation_job",
        "world_asset",
        "world_placement",
        "world_meshy_animation_catalog",
        "world_meshy_animation_slot_option",
    }
    for table in required_tables:
        assert f"CREATE TABLE {table}" in migration

    combined = migration + runtime_sql
    for mysql_token in (
        "ON DUPLICATE KEY",
        "AUTO_INCREMENT",
        "TINYINT",
        "ON UPDATE CURRENT_TIMESTAMP",
        "pymysql",
    ):
        assert mysql_token not in combined

    assert "JSONB" in migration
    assert "GENERATED BY DEFAULT AS IDENTITY" in migration
    assert "ON CONFLICT" in runtime_sql
