-- version: 001
-- purpose: PostgreSQL schema for the 3D asset API
-- apply: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f migrations/001_postgresql_3d_schema.up.sql

BEGIN;

CREATE TABLE agent_settings (
    setting_key VARCHAR(191) PRIMARY KEY,
    setting_value TEXT NOT NULL DEFAULT '',
    description TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE agent_media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'private'
        CHECK (visibility IN ('private', 'public')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_media_asset_user_created
    ON agent_media_asset (user_id, created_at DESC);

CREATE TABLE media_model_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modality VARCHAR(32) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model_id VARCHAR(191) NOT NULL,
    label VARCHAR(191) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 100,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_media_model_catalog_modality_model UNIQUE (modality, model_id)
);

CREATE INDEX idx_media_model_catalog_active_order
    ON media_model_catalog (modality, is_enabled, sort_order, id);

CREATE UNIQUE INDEX uk_media_model_catalog_default
    ON media_model_catalog (modality)
    WHERE is_default AND is_enabled;

CREATE TABLE media_model_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id BIGINT NOT NULL
        REFERENCES media_model_catalog(id) ON DELETE CASCADE,
    option_group VARCHAR(64) NOT NULL,
    option_value VARCHAR(191) NOT NULL,
    label VARCHAR(191) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 100,
    CONSTRAINT uk_media_model_option_value
        UNIQUE (catalog_id, option_group, option_value)
);

CREATE INDEX idx_media_model_option_order
    ON media_model_option (catalog_id, option_group, sort_order, id);

CREATE TABLE media_model_capability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id BIGINT NOT NULL
        REFERENCES media_model_catalog(id) ON DELETE CASCADE,
    capability_key VARCHAR(96) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT,
    CONSTRAINT uk_media_model_capability
        UNIQUE (catalog_id, capability_key)
);

CREATE TABLE agent_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(191) NOT NULL DEFAULT '',
    model VARCHAR(191) NOT NULL DEFAULT '',
    prompt_tokens INTEGER NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
    completion_tokens INTEGER NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
    total_tokens INTEGER NOT NULL DEFAULT 0 CHECK (total_tokens >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_usage_user_created
    ON agent_usage (user_id, created_at DESC);

CREATE TABLE world_generation_job (
    id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sig_id VARCHAR(191),
    session_id VARCHAR(191),
    kind VARCHAR(64) NOT NULL DEFAULT 'house',
    source_image_asset_id BIGINT
        REFERENCES agent_media_asset(id) ON DELETE SET NULL,
    prompt TEXT NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'planned',
    provider_configured BOOLEAN NOT NULL DEFAULT FALSE,
    provider_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_world_generation_job_user_updated
    ON world_generation_job (user_id, updated_at DESC);

CREATE INDEX idx_world_generation_job_sig_updated
    ON world_generation_job (sig_id, updated_at DESC)
    WHERE sig_id IS NOT NULL;

CREATE TABLE world_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sig_id VARCHAR(191),
    job_id VARCHAR(64)
        REFERENCES world_generation_job(id) ON DELETE SET NULL,
    kind VARCHAR(64) NOT NULL,
    source_image_asset_id BIGINT
        REFERENCES agent_media_asset(id) ON DELETE SET NULL,
    label VARCHAR(255) NOT NULL,
    model_url TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'ready',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_world_asset_user_id
    ON world_asset (user_id, id DESC);

CREATE INDEX idx_world_asset_sig_kind_id
    ON world_asset (sig_id, kind, id DESC)
    WHERE sig_id IS NOT NULL;

CREATE TABLE world_placement (
    id VARCHAR(191) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sig_id VARCHAR(191),
    job_id VARCHAR(64)
        REFERENCES world_generation_job(id) ON DELETE SET NULL,
    plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_world_placement_sig_updated
    ON world_placement (sig_id, updated_at DESC, created_at DESC)
    WHERE sig_id IS NOT NULL;

CREATE TABLE world_meshy_animation_catalog (
    action_id INTEGER PRIMARY KEY,
    action_key VARCHAR(160) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(120) NOT NULL,
    sub_category VARCHAR(160) NOT NULL,
    rig_type VARCHAR(80) NOT NULL DEFAULT '',
    tag VARCHAR(120) NOT NULL DEFAULT '',
    preview_url TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_free BOOLEAN NOT NULL DEFAULT FALSE,
    created_at_ms BIGINT NOT NULL DEFAULT 0,
    source_json JSONB,
    synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_world_meshy_animation_catalog_order
    ON world_meshy_animation_catalog
        (category, sub_category, is_free DESC, name, action_id);

CREATE TABLE world_meshy_animation_slot_option (
    slot_key VARCHAR(32) NOT NULL,
    action_id INTEGER NOT NULL
        REFERENCES world_meshy_animation_catalog(action_id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (slot_key, action_id)
);

CREATE INDEX idx_world_meshy_animation_slot_order
    ON world_meshy_animation_slot_option (slot_key, sort_order);

COMMIT;
