-- Island props made with scripts/props (generate.py, then frontend/scripts/props-normalize.mjs) as built-in furniture
-- in every island's decorating drawer. Written by frontend/scripts/props-catalog.mjs; a row only goes in once, so
-- what admins change in the catalog screen (name, order, retiring) stays.
INSERT INTO catalog_items (id, kind, label, emoji, model_url, thumbnail_url, source, status, sort_order) VALUES
  ('prop-door-basic', 'furniture', '현관문', '🚪', '/gltf/decor/door-basic.glb', '/gltf/decor/thumbs/door-basic.webp', 'builtin', 'published', 2000),
  ('prop-window-basic', 'furniture', '창문', '🪟', '/gltf/decor/window-basic.glb', '/gltf/decor/thumbs/window-basic.webp', 'builtin', 'published', 2001),
  ('prop-fence-basic', 'furniture', '울타리', '🪵', '/gltf/decor/fence-basic.glb', '/gltf/decor/thumbs/fence-basic.webp', 'builtin', 'published', 2002),
  ('prop-lamp-basic', 'furniture', '정원 조명', '💡', '/gltf/decor/lamp-basic.glb', '/gltf/decor/thumbs/lamp-basic.webp', 'builtin', 'published', 2003),
  ('prop-chair-basic', 'furniture', '의자', '🪑', '/gltf/decor/chair-basic.glb', '/gltf/decor/thumbs/chair-basic.webp', 'builtin', 'published', 2004),
  ('prop-table-basic', 'furniture', '식탁', '🍽️', '/gltf/decor/table-basic.glb', '/gltf/decor/thumbs/table-basic.webp', 'builtin', 'published', 2005),
  ('prop-bed-basic', 'furniture', '침대', '🛏️', '/gltf/decor/bed-basic.glb', '/gltf/decor/thumbs/bed-basic.webp', 'builtin', 'published', 2006),
  ('prop-storage-basic', 'furniture', '수납장', '🗄️', '/gltf/decor/storage-basic.glb', '/gltf/decor/thumbs/storage-basic.webp', 'builtin', 'published', 2007),
  ('prop-mailbox-basic', 'furniture', '우편함', '📮', '/gltf/decor/mailbox-basic.glb', '/gltf/decor/thumbs/mailbox-basic.webp', 'builtin', 'published', 2008),
  ('prop-crafting-basic', 'furniture', '제작대', '🔨', '/gltf/decor/crafting-basic.glb', '/gltf/decor/thumbs/crafting-basic.webp', 'builtin', 'published', 2009),
  ('prop-shop-stall-basic', 'furniture', '가판대', '🏪', '/gltf/decor/shop-stall-basic.glb', '/gltf/decor/thumbs/shop-stall-basic.webp', 'builtin', 'published', 2010),
  ('prop-flower-pot', 'furniture', '화분', '🪴', '/gltf/decor/flower-pot.glb', '/gltf/decor/thumbs/flower-pot.webp', 'builtin', 'published', 2100),
  ('prop-deco-fountain', 'furniture', '분수', '⛲', '/gltf/decor/deco-fountain.glb', '/gltf/decor/thumbs/deco-fountain.webp', 'builtin', 'published', 2101),
  ('prop-deco-bird-bath', 'furniture', '새 물통', '🐦', '/gltf/decor/deco-bird-bath.glb', '/gltf/decor/thumbs/deco-bird-bath.webp', 'builtin', 'published', 2102),
  ('prop-deco-stone-lantern', 'furniture', '석등', '🏮', '/gltf/decor/deco-stone-lantern.glb', '/gltf/decor/thumbs/deco-stone-lantern.webp', 'builtin', 'published', 2103),
  ('prop-deco-statue-fox', 'furniture', '여우 석상', '🦊', '/gltf/decor/deco-statue-fox.glb', '/gltf/decor/thumbs/deco-statue-fox.webp', 'builtin', 'published', 2104),
  ('prop-deco-statue-bear', 'furniture', '곰 목각상', '🐻', '/gltf/decor/deco-statue-bear.glb', '/gltf/decor/thumbs/deco-statue-bear.webp', 'builtin', 'published', 2105),
  ('prop-deco-sundial', 'furniture', '해시계', '🕰️', '/gltf/decor/deco-sundial.glb', '/gltf/decor/thumbs/deco-sundial.webp', 'builtin', 'published', 2106),
  ('prop-deco-flower-arch', 'furniture', '꽃 아치', '💐', '/gltf/decor/deco-flower-arch.glb', '/gltf/decor/thumbs/deco-flower-arch.webp', 'builtin', 'published', 2107),
  ('prop-deco-bench', 'furniture', '정원 벤치', '🪑', '/gltf/decor/deco-bench.glb', '/gltf/decor/thumbs/deco-bench.webp', 'builtin', 'published', 2108),
  ('prop-deco-well', 'furniture', '우물', '🪣', '/gltf/decor/deco-well.glb', '/gltf/decor/thumbs/deco-well.webp', 'builtin', 'published', 2109),
  ('prop-deco-signpost', 'furniture', '이정표', '🪧', '/gltf/decor/deco-signpost.glb', '/gltf/decor/thumbs/deco-signpost.webp', 'builtin', 'published', 2110),
  ('prop-deco-picnic-table', 'furniture', '피크닉 테이블', '🧺', '/gltf/decor/deco-picnic-table.glb', '/gltf/decor/thumbs/deco-picnic-table.webp', 'builtin', 'published', 2111),
  ('prop-deco-parasol-table', 'furniture', '파라솔 테이블', '⛱️', '/gltf/decor/deco-parasol-table.glb', '/gltf/decor/thumbs/deco-parasol-table.webp', 'builtin', 'published', 2112),
  ('prop-deco-notice-board', 'furniture', '게시판', '📌', '/gltf/decor/deco-notice-board.glb', '/gltf/decor/thumbs/deco-notice-board.webp', 'builtin', 'published', 2113),
  ('prop-farm-scarecrow', 'furniture', '허수아비', '👒', '/gltf/decor/farm-scarecrow.glb', '/gltf/decor/thumbs/farm-scarecrow.webp', 'builtin', 'published', 2200),
  ('prop-farm-hay-bale', 'furniture', '건초 더미', '🌾', '/gltf/decor/farm-hay-bale.glb', '/gltf/decor/thumbs/farm-hay-bale.webp', 'builtin', 'published', 2201),
  ('prop-farm-veg-crate', 'furniture', '채소 상자', '📦', '/gltf/decor/farm-veg-crate.glb', '/gltf/decor/thumbs/farm-veg-crate.webp', 'builtin', 'published', 2202),
  ('prop-farm-wheelbarrow', 'furniture', '손수레', '🛒', '/gltf/decor/farm-wheelbarrow.glb', '/gltf/decor/thumbs/farm-wheelbarrow.webp', 'builtin', 'published', 2203),
  ('prop-farm-watering-can', 'furniture', '물뿌리개', '💧', '/gltf/decor/farm-watering-can.glb', '/gltf/decor/thumbs/farm-watering-can.webp', 'builtin', 'published', 2204),
  ('prop-farm-beehive', 'furniture', '벌통', '🐝', '/gltf/decor/farm-beehive.glb', '/gltf/decor/thumbs/farm-beehive.webp', 'builtin', 'published', 2205),
  ('prop-farm-barrel', 'furniture', '오크통', '🛢️', '/gltf/decor/farm-barrel.glb', '/gltf/decor/thumbs/farm-barrel.webp', 'builtin', 'published', 2206),
  ('prop-crop-pumpkin', 'furniture', '호박밭', '🎃', '/gltf/decor/crop-pumpkin.glb', '/gltf/decor/thumbs/crop-pumpkin.webp', 'builtin', 'published', 2207),
  ('prop-crop-cabbage', 'furniture', '양배추 이랑', '🥬', '/gltf/decor/crop-cabbage.glb', '/gltf/decor/thumbs/crop-cabbage.webp', 'builtin', 'published', 2208),
  ('prop-crop-corn', 'furniture', '옥수수', '🌽', '/gltf/decor/crop-corn.glb', '/gltf/decor/thumbs/crop-corn.webp', 'builtin', 'published', 2209),
  ('prop-crop-wheat', 'furniture', '밀밭', '🌾', '/gltf/decor/crop-wheat.glb', '/gltf/decor/thumbs/crop-wheat.webp', 'builtin', 'published', 2210),
  ('prop-crop-carrot', 'furniture', '당근 이랑', '🥕', '/gltf/decor/crop-carrot.glb', '/gltf/decor/thumbs/crop-carrot.webp', 'builtin', 'published', 2211),
  ('prop-nature-flower-red', 'furniture', '빨간 꽃', '🌺', '/gltf/decor/nature-flower-red.glb', '/gltf/decor/thumbs/nature-flower-red.webp', 'builtin', 'published', 2300),
  ('prop-nature-flower-yellow', 'furniture', '노란 꽃', '🌼', '/gltf/decor/nature-flower-yellow.glb', '/gltf/decor/thumbs/nature-flower-yellow.webp', 'builtin', 'published', 2301),
  ('prop-nature-flower-purple', 'furniture', '보라 꽃', '🪻', '/gltf/decor/nature-flower-purple.glb', '/gltf/decor/thumbs/nature-flower-purple.webp', 'builtin', 'published', 2302),
  ('prop-nature-lily', 'furniture', '연꽃', '🪷', '/gltf/decor/nature-lily.glb', '/gltf/decor/thumbs/nature-lily.webp', 'builtin', 'published', 2303),
  ('prop-flower-tulip-bed', 'furniture', '튤립 화단', '🌷', '/gltf/decor/flower-tulip-bed.glb', '/gltf/decor/thumbs/flower-tulip-bed.webp', 'builtin', 'published', 2304),
  ('prop-flower-sunflower', 'furniture', '해바라기', '🌻', '/gltf/decor/flower-sunflower.glb', '/gltf/decor/thumbs/flower-sunflower.webp', 'builtin', 'published', 2305),
  ('prop-flower-rose-bush', 'furniture', '장미 덤불', '🌹', '/gltf/decor/flower-rose-bush.glb', '/gltf/decor/thumbs/flower-rose-bush.webp', 'builtin', 'published', 2306),
  ('prop-flower-hydrangea', 'furniture', '수국', '💠', '/gltf/decor/flower-hydrangea.glb', '/gltf/decor/thumbs/flower-hydrangea.webp', 'builtin', 'published', 2307),
  ('prop-flower-lavender', 'furniture', '라벤더 화단', '🪻', '/gltf/decor/flower-lavender.glb', '/gltf/decor/thumbs/flower-lavender.webp', 'builtin', 'published', 2308),
  ('prop-flower-daisy', 'furniture', '들꽃 무더기', '🌼', '/gltf/decor/flower-daisy.glb', '/gltf/decor/thumbs/flower-daisy.webp', 'builtin', 'published', 2309),
  ('prop-nature-rock-round', 'furniture', '둥근 바위', '🪨', '/gltf/decor/nature-rock-round.glb', '/gltf/decor/thumbs/nature-rock-round.webp', 'builtin', 'published', 2400),
  ('prop-nature-rock-wide', 'furniture', '넓은 바위', '🪨', '/gltf/decor/nature-rock-wide.glb', '/gltf/decor/thumbs/nature-rock-wide.webp', 'builtin', 'published', 2401),
  ('prop-nature-rock-tall', 'furniture', '높은 바위', '🪨', '/gltf/decor/nature-rock-tall.glb', '/gltf/decor/thumbs/nature-rock-tall.webp', 'builtin', 'published', 2402),
  ('prop-nature-rock-small', 'furniture', '작은 돌', '🪨', '/gltf/decor/nature-rock-small.glb', '/gltf/decor/thumbs/nature-rock-small.webp', 'builtin', 'published', 2403),
  ('prop-nature-rock-flat', 'furniture', '납작 돌', '🪨', '/gltf/decor/nature-rock-flat.glb', '/gltf/decor/thumbs/nature-rock-flat.webp', 'builtin', 'published', 2404),
  ('prop-nature-rock-moss', 'furniture', '이끼 바위', '🪨', '/gltf/decor/nature-rock-moss.glb', '/gltf/decor/thumbs/nature-rock-moss.webp', 'builtin', 'published', 2405),
  ('prop-nature-rock-large', 'furniture', '큰 바위', '🪨', '/gltf/decor/nature-rock-large.glb', '/gltf/decor/thumbs/nature-rock-large.webp', 'builtin', 'published', 2406),
  ('prop-rock-pile-small', 'furniture', '작은 돌무더기', '🪨', '/gltf/decor/rock-pile-small.glb', '/gltf/decor/thumbs/rock-pile-small.webp', 'builtin', 'published', 2407),
  ('prop-rock-pile-large', 'furniture', '큰 돌무더기', '🪨', '/gltf/decor/rock-pile-large.glb', '/gltf/decor/thumbs/rock-pile-large.webp', 'builtin', 'published', 2408),
  ('prop-rock-cairn', 'furniture', '돌탑', '🪨', '/gltf/decor/rock-cairn.glb', '/gltf/decor/thumbs/rock-cairn.webp', 'builtin', 'published', 2409),
  ('prop-rock-boulder-moss', 'furniture', '이끼 덮인 큰 바위', '🪨', '/gltf/decor/rock-boulder-moss.glb', '/gltf/decor/thumbs/rock-boulder-moss.webp', 'builtin', 'published', 2410),
  ('prop-rock-ledge', 'furniture', '층진 바위', '⛰️', '/gltf/decor/rock-ledge.glb', '/gltf/decor/thumbs/rock-ledge.webp', 'builtin', 'published', 2411),
  ('prop-nature-tree-round', 'furniture', '둥근 나무', '🌳', '/gltf/decor/nature-tree-round.glb', '/gltf/decor/thumbs/nature-tree-round.webp', 'builtin', 'published', 2500),
  ('prop-nature-tree-oak', 'furniture', '열매 나무', '🍎', '/gltf/decor/nature-tree-oak.glb', '/gltf/decor/thumbs/nature-tree-oak.webp', 'builtin', 'published', 2501),
  ('prop-nature-tree-pine', 'furniture', '소나무', '🌲', '/gltf/decor/nature-tree-pine.glb', '/gltf/decor/thumbs/nature-tree-pine.webp', 'builtin', 'published', 2502),
  ('prop-nature-tree-fat', 'furniture', '통통한 나무', '🌳', '/gltf/decor/nature-tree-fat.glb', '/gltf/decor/thumbs/nature-tree-fat.webp', 'builtin', 'published', 2503),
  ('prop-nature-tree-thin', 'furniture', '가는 나무', '🌳', '/gltf/decor/nature-tree-thin.glb', '/gltf/decor/thumbs/nature-tree-thin.webp', 'builtin', 'published', 2504),
  ('prop-nature-fern', 'furniture', '고사리', '🌿', '/gltf/decor/nature-fern.glb', '/gltf/decor/thumbs/nature-fern.webp', 'builtin', 'published', 2505),
  ('prop-nature-bush', 'furniture', '덤불', '🍃', '/gltf/decor/nature-bush.glb', '/gltf/decor/thumbs/nature-bush.webp', 'builtin', 'published', 2506),
  ('prop-nature-stump', 'furniture', '그루터기', '🪵', '/gltf/decor/nature-stump.glb', '/gltf/decor/thumbs/nature-stump.webp', 'builtin', 'published', 2507),
  ('prop-nature-fallen-log', 'furniture', '쓰러진 통나무', '🪵', '/gltf/decor/nature-fallen-log.glb', '/gltf/decor/thumbs/nature-fallen-log.webp', 'builtin', 'published', 2508),
  ('prop-nature-mushroom-cluster', 'furniture', '버섯', '🍄', '/gltf/decor/nature-mushroom-cluster.glb', '/gltf/decor/thumbs/nature-mushroom-cluster.webp', 'builtin', 'published', 2509)
ON CONFLICT (id) DO NOTHING;
