#!/usr/bin/env python3
"""Creates the character studio's records database on the shared PostgreSQL, from the server instance over SSM.

The server stack's CharacterDatabaseSecret (generated by CloudFormation: username, password, dbname) names the role and
database; the shared instance's master secret creates them. Nothing secret reaches this machine or the command output.
Safe to run again: it only creates what is missing and resets the role's password to the secret's.
"""
import json
import subprocess
import time

REGION = 'ap-northeast-2'
STACK = 'mogaesup-server'
# The SSM command's own limit, and how long its invocation is waited for past it.
COMMAND_SECONDS = 600
COMMAND_WAIT = COMMAND_SECONDS + 120

SCRIPT = r'''
set -euo pipefail
export PGSSLMODE=verify-full PGSSLROOTCERT=/opt/mogaesup/global-bundle.pem
secret() { aws secretsmanager get-secret-value --region {region} --secret-id "$1" --query SecretString --output text; }
field() { python3 -c 'import json,sys; print(json.load(sys.stdin)[sys.argv[1]])' "$1"; }
MASTER=$(secret '{master}'); APP=$(secret '{app}')
M_USER=$(field username <<<"$MASTER"); M_PW=$(field password <<<"$MASTER")
A_USER=$(field username <<<"$APP"); A_PW=$(field password <<<"$APP"); A_DB=$(field dbname <<<"$APP")
admin() { PGPASSWORD="$M_PW" psql -h '{endpoint}' -U "$M_USER" -v ON_ERROR_STOP=1 -q "$@"; }
admin -d postgres <<SQL
DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$A_USER') THEN CREATE ROLE "$A_USER" LOGIN PASSWORD '$A_PW'; END IF; END \$\$;
ALTER ROLE "$A_USER" LOGIN PASSWORD '$A_PW';
SQL
echo "SELECT 'CREATE DATABASE \"$A_DB\"' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$A_DB')\gexec" | admin -d postgres
admin -d "$A_DB" -c "GRANT ALL ON DATABASE \"$A_DB\" TO \"$A_USER\"; GRANT USAGE, CREATE ON SCHEMA public TO \"$A_USER\";"
PGPASSWORD="$A_PW" psql -h '{endpoint}' -U "$A_USER" -d "$A_DB" -v ON_ERROR_STOP=1 -Atc "SELECT current_user, current_database()"
'''


def aws(*args):
    return json.loads(subprocess.check_output(['aws', *args, '--region', REGION, '--output', 'json']))


def main():
    outputs = {item['OutputKey']: item['OutputValue']
               for item in aws('cloudformation', 'describe-stacks', '--stack-name', STACK)['Stacks'][0]['Outputs']}
    script = SCRIPT.replace('{region}', REGION).replace('{master}', outputs['DatabaseSecretArn']) \
        .replace('{app}', outputs['CharacterDatabaseSecretArn']).replace('{endpoint}', outputs['DatabaseEndpoint'])
    parameters = json.dumps({'commands': ["cat > /var/tmp/character-database.sh <<'SETUP'", *script.strip().splitlines(), 'SETUP',
                                          'bash /var/tmp/character-database.sh; status=$?; rm -f /var/tmp/character-database.sh; exit $status'],
                             'executionTimeout': [str(COMMAND_SECONDS)]})
    command = aws('ssm', 'send-command', '--instance-ids', outputs['InstanceId'], '--document-name', 'AWS-RunShellScript',
                  '--parameters', parameters, '--comment', 'character records database')['Command']['CommandId']
    deadline = time.monotonic() + COMMAND_WAIT
    while True:
        time.sleep(4)
        try:
            result = aws('ssm', 'get-command-invocation', '--command-id', command, '--instance-id', outputs['InstanceId'])
        except subprocess.CalledProcessError:
            result = None
        if result and result['Status'] not in ('Pending', 'InProgress', 'Delayed'):
            break
        if time.monotonic() > deadline:
            raise SystemExit(f'setup did not finish within {COMMAND_WAIT} s; inspect SSM command {command} on the instance')
    print(result['StandardOutputContent'], result['StandardErrorContent'])
    if result['Status'] != 'Success':
        raise SystemExit(f"failed: {result['Status']}")


if __name__ == '__main__':
    main()
